apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: llamastack

resources:
  - namespace.yaml
  - configmap-mcp-endpoints.yaml
  - secret.yaml
  - llamastackdistribution.yaml
  - route.yaml

configMapGenerator:
  - name: llamastack-server-config
    files:
      - config.yaml=config/config.yaml
    options:
      disableNameSuffixHash: true
