apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: agentic-demo

resources:
  - namespace.yaml
  - github-mcp-secret.yaml
  - github-mcp.yaml
  - configmap-mcp-endpoints.yaml
  - secret.yaml
  - llamastackdistribution.yaml
  - route.yaml
  - llama-stack-ui.yaml
  - route-ui.yaml

configMapGenerator:
  - name: llamastack-server-config
    files:
      - config.yaml=config/config.yaml
    options:
      disableNameSuffixHash: true
