apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: llamastack-ui
  namespace: agentic-demo
spec:
  to:
    kind: Service
    name: llamastack-ui
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
